#!/bin/bash

set -euox pipefail

apt-get update -y
apt-get install vim git wget -y
useradd cgalan
usermod -G sudo cgalan
echo "AllowUsers cgalan" >> /etc/ssh/sshd_config

mkdir -p /cgalan/.ssh
chmod 600 /cgalan/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7ItY9Ka5l4EUQP84gcQYjrG5peF/Y/+UgYjE+p3GRtlSSg4KonlwEYM/iOrLbVl5GqDMRgvKBQQn3p4GmdnYVmorHqhV9OOycjBgpl0IB4GM8Sw7SM/KxDFE3Iy8zyjnTnKV/qOLX0AFArnxSrsriXHCVUdPVC4QTWMcIL3ZNvpPCbjzInbLnBphpgtkOtHsPW6ZLEShVUEn5SuDcL/NiAKQ6QIYbPPLMM2RtJA4v1H5xlrQ2V8eBmluvgd598FNFv cgalan@DESKTOP-BRT4P2N" > /cgalan/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6nlGLRvUZPJoFyT/QbH4SH26PQNRaiBRxLGClWJdMDLQaSzW7FEzghIX/6UFwvSIZrcSK/YxWmanBeWQipn1yDeK6P9IGGVFFzA6zjvObBfs76o4cOMZIVcjx5xuvmyzF0SNCKZqZF+vdoD/Pu0jukjs0TVo0Ao19+M/wBDM76r51RJsS3H2sMhTn7W8rMRazRY1VbKIskd51hfmXrT/o5N08NyggIaEjWNdFvtG0sRcKCDISBjVXfJT/FxsZy/HT40ogNud3IaA2WYfSwITeECcM87C5YpzClwGx06qfwZksMmi5M4UEqHD8ym+ZbmUofKNNA2VF2k1Lk3smGGPDvgCLkAomHBayEksjfhFzY1PBGFvN3O3CG6JGJfBeeQkOv6Yui9Z49x6pzWG19LKctwo8IkqWD9P8pGgjITfxgK0qohWEc6f6/ik4mvcWkERd8L7ezX7drq8aZZ2Q4mMWNivfhGWf1cM7W5y/GTrk+8+tE4cXNytlOttxLRBdqc6P6YOR+lJNBxV2P1uCBupTBGD3VOBDdxAHUMwo2mwKemG/SG/7kMioS4/1xqd52YPs8dV+nFDXvyzg9yI31vQ4DQ+TlM8u4mQ+ZnKr4G0m0o2eUnugpkrHLS0nG6N5FzPxtTTTDDwA1x4gmh7OOo+qukfZxCRWomqiKfJKEgnsgQ== Generated by galan@DESKTOP-BRT4P2N." > /cgalan/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxpRYrwzXIn8KEV/6v8OrJn4TSmcPftse22Re3RgtjV69dVFfoVEqujL3Lqy/wdPl+EjCD2CuVIWIdzPyuRs/ejiW1QMQuAuneoXkyJKelJqH1vBz//PrTib/Aw0vLvUoZfPgBMo6/UwUmXuX01m/mLrRXEizPJXqXajY+rmRjKbFnHWNLitnYhWmD7MuXBOJhqZ00CzO6qUJ5NI4qmM1mZpnjYswj2N94s56zSLubJZ1UCJiXPgDBdHIT/L+5y7uVMW6+2hYjnzxfoVC4rBKzMlU2ZiJpa1WssSOsAuobAIW4q6Fpbjp+YQ4WkJ9xNbnBBMU6TtnsxbRmETemGAeuar2/hUl3z1HTwOY7lqhKQLlxRiEubMPI8pZwSpx4oHelvzx3VquRMQaLNuKt76dC0f0NPHgu6C4Llgw820rDTmNWAz4pCMrpV8QTK2zBpfjNfLbFBuPan1G/c9v/+Di7XHyQ8bnUBhKoDVpMuuAZEkJObpLFdel2Bx+jRPtFrnpYO5lsAilpa1qEj2Y2BLfIA2vwyTOLD5qJ7qeg8189D0YT5iuz6S63yL8aaCr34R8sLXOkqFIJw9WCPRhkcZSUOGZ+i4vAj0NqauNnSFOWmMkto4edSjBGnr5DExdw+UmQG8X5Ph8lXMoq5L77l4WpUVWdbV8qA1z8Dd8eZ5wVDw== cgalan@ansible" > /cgalan/.ssh/authorized_keys
chmod 700 /cgalan/.ssh/authorized_keys

apt-get install fail2ban
touch /etc/fail2ban/jail.local
echo "[ssh-iptables]" >> /etc/fail2ban/jail.local
echo "enabled = true" >> /etc/fail2ban/jail.local
echo "filter = sshd" >> /etc/fail2ban/jail.local
echo "action = iptables[name=SSH, port=ssh, protocol=tcp]" >> /etc/fail2ban/jail.local
echo "logpath = /var/log/auth.log" >> /etc/fail2ban/jail.local
update-rc.d fail2ban defaults

reboot

